/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActiveRouteImport } from './routes/active'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiPatientsRouteImport } from './routes/api/patients'
import { Route as ApiPatientsPatientIdRouteImport } from './routes/api/patients/$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveRoute = ActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatientsRoute = ApiPatientsRouteImport.update({
  id: '/api/patients',
  path: '/api/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatientsPatientIdRoute = ApiPatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => ApiPatientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/active': typeof ActiveRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/api/patients': typeof ApiPatientsRouteWithChildren
  '/api/patients/$patientId': typeof ApiPatientsPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/active': typeof ActiveRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/api/patients': typeof ApiPatientsRouteWithChildren
  '/api/patients/$patientId': typeof ApiPatientsPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/active': typeof ActiveRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/api/patients': typeof ApiPatientsRouteWithChildren
  '/api/patients/$patientId': typeof ApiPatientsPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/active'
    | '/history'
    | '/settings'
    | '/api/patients'
    | '/api/patients/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/active'
    | '/history'
    | '/settings'
    | '/api/patients'
    | '/api/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/active'
    | '/history'
    | '/settings'
    | '/api/patients'
    | '/api/patients/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActiveRoute: typeof ActiveRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  ApiPatientsRoute: typeof ApiPatientsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active': {
      id: '/active'
      path: '/active'
      fullPath: '/active'
      preLoaderRoute: typeof ActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patients': {
      id: '/api/patients'
      path: '/api/patients'
      fullPath: '/api/patients'
      preLoaderRoute: typeof ApiPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patients/$patientId': {
      id: '/api/patients/$patientId'
      path: '/$patientId'
      fullPath: '/api/patients/$patientId'
      preLoaderRoute: typeof ApiPatientsPatientIdRouteImport
      parentRoute: typeof ApiPatientsRoute
    }
  }
}

interface ApiPatientsRouteChildren {
  ApiPatientsPatientIdRoute: typeof ApiPatientsPatientIdRoute
}

const ApiPatientsRouteChildren: ApiPatientsRouteChildren = {
  ApiPatientsPatientIdRoute: ApiPatientsPatientIdRoute,
}

const ApiPatientsRouteWithChildren = ApiPatientsRoute._addFileChildren(
  ApiPatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActiveRoute: ActiveRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
  ApiPatientsRoute: ApiPatientsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
